@startuml

title __MODEL's Class Diagram__\n

  namespace  {
    namespace o.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.City {
            - ID : String
            - cityName : String
            - countryName : String
            - latitude : String
            - longitude : String
            + City()
            + getCityName()
            + getCountryName()
        }
      }
    }
  }
  

  namespace  {
    namespace o.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.Country {
            - cities : ArrayList<City>
            - countryName : String
            + Country()
            + addCity()
            + getCountryName()
            + printCities()
        }
      }
    }
  }
  

  namespace  {
    namespace o.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.OpenWeatherMapAPI {
            - cityName : String
            - countryName : String
            {static} - instance : OpenWeatherMapAPI
            {static} - keyAPI : String
            - urlAPI : String
            {static} + getInstance()
            + getJSONResponse()
            + getUrlAPI()
            - OpenWeatherMapAPI()
        }
      }
    }
  }
  

  namespace  {
    namespace o.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.convertFromKelvinToCelsius {
            - CelsiusDegree : String
            - KelvinDegree : double
            + convertDegree()
            + getXDegree()
            + verify()
        }
      }
    }
  }
  

  ro.mta.se.lab.model.convertFromKelvinToCelsius .up.|> ro.mta.se.lab.interfaces.convertFromXToX


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
