@startuml

title __CONTROLLER's Class Diagram__\n

  namespace  {
    namespace o.mta.se.lab {
      namespace controller {
        class ro.mta.se.lab.controller.PrimaryController {
            ~ KelvinDegree : float
            - citiesToAdd : ArrayList<City>
            - city : ComboBox<String>
            - cityName : Label
            - country : ComboBox<String>
            - dayTime : Label
            - dayTimeText : String
            - degree : Label
            - degree1 : Label
            - degreeText : String
            - description : Label
            - descriptionText : String
            - humidity : Label
            - humidityText : String
            - iconText : String
            - locationMap : HashMap<Country, ArrayList<City>>
            - precipitation : Label
            - precipitationText : String
            - showButton : Button
            - sunrise : Label
            - sunriseLong : Long
            - sunriseText : String
            - sunset : Label
            - sunsetLong : Long
            - sunsetText : String
            - weatherIcon : ImageView
            - wind : Label
            - windText : String
            + PrimaryController()
            + convertKelvinToCelsius()
            + countHoursTimezone()
            + handleShowButton()
            + initialize()
            + verify()
            - convertUnixTimeToRealTime()
            - downloadIcon()
            - handleCity()
            - handleCountry()
            - logInFile()
            - parseJson()
            - setCity()
            - updateLabels()
        }
      }
    }
  }
  

  ro.mta.se.lab.controller.PrimaryController .up.|> javafx.fxml.Initializable
  ro.mta.se.lab.controller.PrimaryController o-- ro.mta.se.lab.model.convertFromKelvinToCelsius : convert


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
